### ISSUE TITLE
Dew point temperature does only update on pimatic (re)start

### ISSUE THREAD

**Issue by AnduriI** [flybysun/dev-pimatic-dewpoint#4]
Hi,

temperature of the device does not update during normal operation of pimatic, only when I restart pimatic. Problem seems to have start on 8th of feb. There was another problem with homeduino at this time which misread the temp to 48°C, but this was solved. Maybe it is somehow connected.

![pimatic-dewpoint](https://cloud.githubusercontent.com/assets/12829391/13547746/70a4583a-e2de-11e5-9328-a3e4bf1b7dc1.PNG)

**Comment by mwittig** [comment]
Works for me! I think this issue can be closed unless there are new findings!

![screenshot](https://gist.githubusercontent.com/mwittig/7fc81ae221314d36610d/raw/fa10c11e7e0fe5210f29762744521d5b4edac72d/dewpoint.png)

**Comment by AnduriI** [comment]
still the same problems for me. I updated today (dew-point 0.8.3 and homeduino 0.8.73) but I only get an updated temperatur at restart of pimatic. I will post a screenshot after some time of data acquisition with these updated system.

**Comment by mwittig** [comment]
Ok, I'll also keep an eye on this.

**Comment by AnduriI** [comment]
![pimatic-dewpoint_2016-04-10](https://cloud.githubusercontent.com/assets/12829391/14412755/c4854b88-ff69-11e5-9819-6952d7f666d6.PNG)

Here my update. Still only getting very little updates on temperature. Humidity gets updates frequently with every update on the real device. I'll post the config of those two devices, just in case there is a bad config on my side.

```
    {
      "id": "Aussen1",
      "name": "Außensensor Wohnzimmer",
      "class": "HomeduinoRFWeatherStation",
      "protocols": [
        {
          "name": "weather9",
          "options": {
            "id": 59,
            "channel": 1
          }
        }
      ],
      "values": [
        "temperature",
        "humidity"
      ]
    },
    [...]
    {
      "id": "dew",
      "class": "DewPointDevice",
      "name": "Dew Point",
      "temperatureRef": "$Aussen1.temperature",
      "humidityRef": "$Aussen1.humidity"
    },
```

**Comment by AnduriI** [comment]
short update: I tested with another source for temp and hum (a mysensors node) which seems to work fine. Temperature is updated as expected. Maybe this is related more to homeduino than dew-point. Can you confirm that @mwittig?

**Comment by mwittig** [comment]
Yes, it working fine for me with another source and wanted to set-up with homeduino tonight. Possibly a problem with homeduino as you say.

**Comment by mwittig** [comment]
@AnduriI Recently, I found a nasty typo in the HomeduinoRFWeatherStation and HomeduinoRFTemperature device class implementations which caused the temparture variables did not update properly. This should be fixed now with the latest pimatic-homeduino release and thus, dewpoint temperature should be updated properly now in your setup.

**Comment by AnduriI** [comment]
@mwittig yep, it's working again. Thanks
