### ISSUE TITLE
0.8.4

### ISSUE THREAD

**Issue by mwittig** [flybysun/dev-pimatic-dewpoint#6]
For info, I have published 0.8.4 on my fork and set the homepage to my fork for now, as I don't have access to your github repo. The pending PR contains all changes made.

**Comment by flybysun** [comment]
Hi Markus,
I haven't been around here for a while, sorry about that. I also didn't check my GitHub Mails. 
I've added you as a collaborator! Thanks for helping and supporting!

Regards

2016-05-28 11:07 GMT+02:00 Marcus Wittig notifications@github.com:

**Comment by mwittig** [comment]
Thanks for adding me. I have switched settings back with the latest release!
