### ISSUE TITLE
[solved] plugin chrashes pimatic V0.9.38 when processing temperature data from mqtt-devices

### ISSUE THREAD

**Issue by fennsen64** [flybysun/dev-pimatic-dewpoint#8]
the new version crashes my pimatic when processing temperature data arriving from mqtt temperature sensors.

After investigating the changes which has been made to this pimatic-dewpoint plugin: this has been changed in some parts (i used V 0.8 in the current pimatic 0.8.107 setup which works flawless): esp. the format (see device-config-schema.coffee ) has changed from “string” to “metric”:

deleted type: "string"
added enum: [“metric”, “imperial”, “standard”]
default: “metric”

Therefore the question is: has there been any pimatic internal changes in V0.9 how number-units are handled???
There seems to be a new choice between “metric”, “imperial”, “standard”.

My input data from mqtt-devices are normal 'number’s

See detailed description of the issue and questions in the forum:
[https://forum.pimatic.org/topic/2848/pimatic-dewpoint-with-mqtt-plugin-problem-memory-migration-to-v0-9-not-possible-moved/2](url)

**Comment by mwittig** [comment]
I don't think the change of the "units" type is a problem.  Do you get an exception filed in the log? Please check the log file for error message and post them in case

**Comment by fennsen64** [comment]
Hi, we can close it. The issue was references to expression variables (see my add on in the forum post). Thanks!

**Comment by mwittig** [comment]
https://forum.pimatic.org/topic/2848/solved-pimatic-dewpoint-with-mqtt-plugin-problem-memory-migration-to-v0-9-not-possible-moved/3
